### ISSUE TITLE
Feature request: Drag'n'Drop to arrange courses

### ISSUE THREAD

**Issue by Jarvil** [thepurpleblob/moodle-block_course_overview#1]
Hello,

At the moment if you turn editing on dashboard/my moodle you cannot drag courses to order of your liking as easily as before because you can move them by only clicking the up/down-arrow and by clicking the empty space where to move them.

I would like to see drag'n'drop feature that was in Moodle 3.1 so you could arrange your courses more easily.

![selection_253](https://user-images.githubusercontent.com/15193418/29967635-44b4a7a8-8f20-11e7-8ecc-11a86437ffe8.png)

![selection_252](https://user-images.githubusercontent.com/15193418/29967644-49bbe086-8f20-11e7-8ace-e4247293dab7.png)

**Comment by thepurpleblob** [comment]
This *should* be fixed. Make sure you have the latest 'master' version from here. 

There was a problem in the Javascript Bit. Let me know how you get on.

**Comment by thepurpleblob** [comment]
Closed in 3.3.2
