### ISSUE TITLE
Block CSS doesn't indicate when a course is hidden

### ISSUE THREAD

**Issue by chrismyers81** [thepurpleblob/moodle-block_course_overview#11]
With the regular Course Overview block, when a course is "hidden" the color of the link will change to indicate as such. However, with the legacy block, there isn't a differentiation, so faculty aren't able to tell at a glance that they've neglected to enable their course for their students. This sounds similar to the issue with the regular Moodle course overview block that was fixed a couple of months ago: https://tracker.moodle.org/browse/MDL-59492

**Comment by thepurpleblob** [comment]
Which theme are you using?

**Comment by chrismyers81** [comment]
The new Boost one.
