### ISSUE TITLE
New courses to the top of the list

### ISSUE THREAD

**Issue by Jarvil** [thepurpleblob/moodle-block_course_overview#12]
Hi,

Newly created courses should appeared at the top of the course overview block. At present they appear at the bottom.

see also;

https://moodle.org/mod/forum/discuss.php?d=350008

**Comment by thepurpleblob** [comment]
Well... I'm not sure they should. This would put them 'above' courses that a user had dragged to the top to make it *their* most important course. Unless I'm missing something. Effectively we would need to override user's custom list of courses - which I don't think I agree with.

**Comment by Jarvil** [comment]
I think most users don't drag their courses by themselves and would appriciate newest ones on the top automatically, anyway you can make it as an option so people can toggle it on if necessary?

**Comment by thepurpleblob** [comment]
I'm basically struggling to see the concept of "new courses". Newly created courses are typically empty and unused (at least for a while).  There is already an option to show recently accessed courses instead of a custom sort order. 

I think that "order by creation" date is probably niche.

**Comment by thepurpleblob** [comment]
Are you sure? New courses, in my experience anyway, are almost always empty courses. 

Do you mean "the most recently created courses that the user is enrolled in" or "the user's most recent enrolment date on a given course"?

**Comment by Jarvil** [comment]
Hello,

I'm sure since this was a direct message from our end customer using the Moodle. By new I mean "the user's most recent enrolment date on a given course"

**Comment by thepurpleblob** [comment]
Ok that's a slightly different thing from 'new course'. I'll have a look at adding 'date enrolled' as a possible sort option.

**Comment by bel-omahoney** [comment]
Hello! I have created a pull request for this issue (Add course sort order "Course id desc" #36). This adds Course id desc without changing / removing Course id (asc) so users can choose what makes the most sense to them. Thanks!

**Comment by thepurpleblob** [comment]
Change has been merged. Thanks @bel-omahoney
