### ISSUE TITLE
dialogue close button/icon alignment

### ISSUE THREAD

**Issue by mnods** [thepurpleblob/moodle-block_course_overview#14]
a bit off in essential and clean from what i can see - button is aligned left and is a little too small - what i put in to align for us:
 
.course-overview-dialog .ui-dialog-titlebar button{
background-color: #fff;
background-image:none;
height: 25px;
position: absolute;
top: 8px;
right: 13px;
}
.course-overview-dialog .ui-dialog-titlebar-close::after{   
top: 1px;
left: 1px;   
}

**Comment by thepurpleblob** [comment]
It's still not quite right but is definitely better. I'll add your solution - thanks.
