### ISSUE TITLE
Missing lang string

### ISSUE THREAD

**Issue by atronat** [thepurpleblob/moodle-block_course_overview#19]
![string](https://user-images.githubusercontent.com/40802334/42231916-914652b8-7ef5-11e8-9f0d-bc57bd1520f3.png)
Maybe it makes sense to rewrite settings.php like this (rows 49-54):
        BLOCKS_COURSE_OVERVIEW_DEFAULT_COURSES => new lang_string('courses'),
    ];
    $settings->add(new admin_setting_configselect(
        'block_course_overview/defaulttab',
        new lang_string('defaulttab', 'block_myoverview'),
        new lang_string('defaulttab_desc', 'block_myoverview'),

**Comment by thepurpleblob** [comment]
I don't really understand. Why would I do that? it makes the strings dependent on another plugin. 

If you had updated to the latest version then the caches would automatically be purged and you should see the new strings.

Or am I missing something?

**Comment by atronat** [comment]
>it makes the strings dependent on another plugin. 

Agree, using strings from another plugin is a bad idea :)

> Or am I missing something?

Yes, in the language file _block_course_overview.php_ missing this strings:

- 'courses'
- 'defaulttab'
- 'defaulttabdesc'

**Comment by thepurpleblob** [comment]
Aargh... sorry. I forgot to copy the revised language file over
