### ISSUE TITLE
Bug: Cannot move blocks if you have due activities

### ISSUE THREAD

**Issue by Jarvil** [thepurpleblob/moodle-block_course_overview#2]
Hello,

If you have courses that has due activities or anything else that is shown under course name you cannot arrange/change position of blocks on my course page.

**Comment by thepurpleblob** [comment]
I can't reproduce this. I have a test user who has an assignment due and can move the courses about fine. Make sure you have the latest version. Failing that, will need more info.

**Comment by thepurpleblob** [comment]
Closed in version 3.3.2
