### ISSUE TITLE
Course links aren't clickable in edit mode

### ISSUE THREAD

**Issue by david-polymtl** [thepurpleblob/moodle-block_course_overview#26]
When in edit mode (either from clicking 'Modify this page' or by editing a course, not leaving edit mode and going back to the dashboard), it is not possible to click on a course link before getting out of the edit mode first. We've had a complaint from a teacher saying this was not efficient when editing content from one course to another with the back and forth between modes all the time just to be able to click the course links.

We're running Moodle version 3.4.4.

By the way, this plugin has saved us from very angry teachers not liking the new Moodle dashboard at all, so thanks for your work!

![links_01](https://user-images.githubusercontent.com/32393849/44222375-4ca3e600-a152-11e8-9e0e-b53de170683b.jpg)
![links_02](https://user-images.githubusercontent.com/32393849/44222376-4ca3e600-a152-11e8-80a1-548129d12c74.jpg)

**Comment by thepurpleblob** [comment]
I haven't quite made my mind up, but I'm thinking about getting rid of 'edit mode' completely. 

Any thoughts appreciated.

**Comment by Jarvil** [comment]
Hello,

if a teacher sets editing on a course and returns to Dashboard he/she cannot click course names in the course overview (legacy) -block. I would like to see this changed so that they can click the links. If you don't have edit mode how can people then arrange the order of their courses and favorites?

**Comment by thepurpleblob** [comment]
I mean that you can change the order any time. Maybe there should be a 'lock' icon on the block?

**Comment by Jarvil** [comment]
Hello,

Coudn't course edit mode and course overview -block edit mode be two separate things? This way they woudn't interfere with each other?

**Comment by david-polymtl** [comment]
I think the most practical dummy proof way to do it is to replicate a course page default behaviour, meaning to move items around you need to be in edit mode, but the links to the activities remain clickable. That way teachers already know how to interact with it and it's not like you'll want to rearange these links every other day anyway. You usually set it and forget it.

Being able to move them at all times without the need to be in edit mode is a good solution too, as long as they can't easily be accidently moved while trying to click them.

I think both those solutions hit the mark.

**Comment by bel-omahoney** [comment]
Hello, I have just created a pull request for this issue (Retain course link in edit mode #35). The course name links remain clickable in edit mode and are still able to be re-ordered. Thanks!

**Comment by kattekrab** [comment]
We've been asked to do this too! +1

**Comment by kattekrab** [comment]
@tsmilan - how does this compare with your solution?

**Comment by thepurpleblob** [comment]
This has been fixed by @bel-omahoney  (thanks!)
