### ISSUE TITLE
Bug: Favourites and Courses-tab content changes place permanently

### ISSUE THREAD

**Issue by Jarvil** [thepurpleblob/moodle-block_course_overview#28]
Hello,

there is a bad bug in the course overview (legacy), tested on version 3.5.4
2018070400 & Moodle 3.3

Favourites and Courses tab content changes place **permanently.**

0. Enrol student1 to course A, course B, course C and course D.
1. Notice that the default order of the tabs are Favourites and Courses
2. Mark course A and course B as your favorites (course C and D will remain on the courses-tab)
2. Click "customize this page"
3. Go to courses-tab and change the order of course C and course D and click "stop customising this page"
4. Notice how Favourites and Courses that content are now changed with each other. 

Favourites-tab now have course C and D 
and 
Courses-tab now have course A and B.

![course1](https://user-images.githubusercontent.com/15193418/45403616-10d24280-b664-11e8-9904-6c38681f53a6.PNG)

![course2](https://user-images.githubusercontent.com/15193418/45403619-14fe6000-b664-11e8-8d9e-002aed91a77b.PNG)

![course3](https://user-images.githubusercontent.com/15193418/45403621-19c31400-b664-11e8-8136-950ac4e627e8.png)

![course4](https://user-images.githubusercontent.com/15193418/45403623-1c256e00-b664-11e8-9858-4796ff140315.png)

![course5](https://user-images.githubusercontent.com/15193418/45403627-1f205e80-b664-11e8-99bc-94c71501b292.png)

@thepurpleblob

**Comment by thepurpleblob** [comment]
Thanks for the detailed explanation. I'm currently working on a substantial update and will make sure this is fixed.

**Comment by bel-omahoney** [comment]
Hello, I have created a pull request to fix this issue (Send correct tab name when editing course order #37). Note that this is theme related and is not an issue in some themes. Thanks!

**Comment by thepurpleblob** [comment]
This should be fixed. Thanks @bel-omahoney
