### ISSUE TITLE
Course order does not stick

### ISSUE THREAD

**Issue by cdipe** [thepurpleblob/moodle-block_course_overview#29]
When having selected **Customise this page** and Sort order as **Drag-and-drop order**, I can sort the order of my courses both in the Courses tab and the Favourites tab. But, when clicking **Stop customising this page**, they all go back to their previous order. 

I have set **Sort my courses** to **Sort order** on https://mymoodle.qa.lnu.se/admin/settings.php?section=navigation, but to no use. And I guess that shouldn't matter anyway.
Using Moodle 3.4.4 and Course Overview (Legacy) 3.5.4

**Comment by thepurpleblob** [comment]
Ok - thanks for the update.
