### ISSUE TITLE
Bug: huge amount space between courses when you are moving them

### ISSUE THREAD

**Issue by Jarvil** [thepurpleblob/moodle-block_course_overview#3]
Hello,

if you set editing on and click up/down arrow to change position of course you get huge amount space between courses which makes moving them really difficult. You need to have at least two courses on which you have student/teacher role and due assignment on these courses.

![image pasted at 2017-9-1 14-31](https://user-images.githubusercontent.com/15193418/29968018-60e68ba6-8f22-11e7-927c-a769d6422821.png)

![image pasted at 2017-9-1 14-32](https://user-images.githubusercontent.com/15193418/29968046-8e9a35ca-8f22-11e7-87d2-0249eaaee525.png)

**Comment by thepurpleblob** [comment]
This was the same problem as the drag-and-drop. Boost had changed the layout and the javascript was no longer adding the correct classes. It should be fixed. 

Try the latest version and let me know how you get on.

**Comment by thepurpleblob** [comment]
Closed in version 3.3.2
