### ISSUE TITLE
Please remove " (Legacy)" from block title

### ISSUE THREAD

**Issue by foxlapinou** [thepurpleblob/moodle-block_course_overview#30]
Please remove " (Legacy)" from block title because it's shown on user interface, and they don't understand this. Of course, it can be let on block name.

**Comment by thepurpleblob** [comment]
I am in the process of creating an update to this block and it's already done. Hopefully out soon (other stuff permitting)

**Comment by foxlapinou** [comment]
Good news :-)
Thanks, and keep up the good work (if you can).

**Comment by thepurpleblob** [comment]
To avoid massive confusion, I changed it to 'Course tabbed overview'. You can obviously change it to whatever you like in the language customisation.
