### ISSUE TITLE
Exception on user dashboard

### ISSUE THREAD

**Issue by anieminen** [thepurpleblob/moodle-block_course_overview#39]
Hi,

We have a problem when a user is trying to access dashboard with Course overview block added: 

![exception](https://user-images.githubusercontent.com/15781654/55792265-f3196e80-5ac8-11e9-876a-4cb32f2529ee.PNG)

There is a related issue in Moodle Tracker: https://tracker.moodle.org/browse/MDL-52609
As stated in the last comment, this error can be fixed with a patch to Moodle core. But the problem seems to be that Course overview block is using deprecated `print_overview()` functions. Is this something that could be fixed in the block code?

**Comment by thepurpleblob** [comment]
Yep - this is the 'legacy' aspect. We still call this old function. My plan is to make it an option to call the new functions but they do act rather differently. Eventually, the old functions will be removed. They're still there in 3.7 however.
