### ISSUE TITLE
Behat and phpunit report broken plugin

### ISSUE THREAD

**Issue by ewallah** [thepurpleblob/moodle-block_course_overview#4]
Default exception handler: Plugin "block_myoverview" is defective or outdated, can not continue, sorry. Debug: Naming conflict: block myoverview has the same title with an existing block: course_overview!
Error code: detectedbrokenplugin
* line 897 of /lib/upgradelib.php: plugin_defective_exception thrown
* line 446 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1754 of /lib/upgradelib.php: call to upgrade_plugins()
* line 491 of /lib/installlib.php: call to upgrade_noncore()
* line 86 of /lib/behat/classes/util.php: call to install_cli_database()
* line 160 of /admin/tool/behat/cli/util_single_run.php: call to behat_util::install_site()

Default exception handler: Plugin "block_myoverview" is defective or outdated, can not continue, sorry. Debug: Naming conflict: block myoverview has the same title with an existing block: course_overview!
Error code: detectedbrokenplugin
* line 897 of /lib/upgradelib.php: plugin_defective_exception thrown
* line 446 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1754 of /lib/upgradelib.php: call to upgrade_plugins()
* line 491 of /lib/installlib.php: call to upgrade_noncore()
* line 457 of /lib/phpunit/classes/util.php: call to install_cli_database()
* line 150 of /admin/tool/phpunit/cli/util.php: call to phpunit_util::install_site()

Moodle 3.3.2+ (Build: 20170928)
Php: 7.1.10.1.16.04.1.1, pgsql: 9.5.9, OS: Linux 4.4.0-96-generic x86_64
PHPUnit 5.5.7

Can be fixed by changing $string['title'] = 'Course overview'; => $string['title'] = 'Course overview old';

**Comment by thepurpleblob** [comment]
I must confess that I know absolutely nothing about Behat.

Your solution seems logical though

**Comment by ewallah** [comment]
This fixes the functionality of behat and phpunit.
But about 11 behat tests fail because they are not written with the new version in mind.

**Comment by thepurpleblob** [comment]
Ok... I'd better go and read the Behat documentation.
