### ISSUE TITLE
Messy lay-out in theme boost

### ISSUE THREAD

**Issue by wmcmps** [thepurpleblob/moodle-block_course_overview#5]
Since the recent update to version 2017112800, the lay-out is very messy on small screens. The links to some courses even don't work when they are behind another course. We use theme boost. I guess we are not the only ones having this problem. Is this something you could help us with?

![theme boost](https://user-images.githubusercontent.com/10821510/33422219-43e7c55e-d5b5-11e7-9833-8afe86f17a96.jpg)

**Comment by thepurpleblob** [comment]
I did do the development work using Boost, so that's quite odd. I also checked with smaller screens. What browser is this and how small is small?

**Comment by wmcmps** [comment]
It happens in every popular browser (Edge, Firefox, Chrome, Opera). 
![browsers](https://user-images.githubusercontent.com/10821510/33427081-54c64bd4-d5c4-11e7-83eb-58405a05af03.jpg)

It happens when the course name doesn't fit on one line. And since our school has very long course names, it happens a lot (even on 1280px and more).

**Comment by thepurpleblob** [comment]
Yep - I'm rewriting the way that bit is laid out. Back soon :)

**Comment by wmcmps** [comment]
Thanks :-)))

**Comment by thepurpleblob** [comment]
Can you try the latest version from github and see if it helps please?

**Comment by wmcmps** [comment]
It is looking better now. Not optimal but there is no overlap anymore. Many thanks. I'll ask my colleagues if they still encounter problems.

![new version](https://user-images.githubusercontent.com/10821510/33442673-0347dcb4-d5f6-11e7-931d-1a3aeeb9a03a.jpg)

**Comment by thepurpleblob** [comment]
Still looks odd for you. I'm struggling to reproduce the problems you are seeing. Is this site remotely accessible (with a suitable test user) so I could see what's going on?

**Comment by wmcmps** [comment]
We are running version 3.3. I have sent you an email with test user details.

**Comment by thepurpleblob** [comment]
That's great... I'll have a look later on today and get it sorted out (hopefully!)

**Comment by thepurpleblob** [comment]
Could you try purging your caches? There are some CSS changes. I'll change the version number when released properly.

**Comment by wmcmps** [comment]
This looks much better now. Thanks a lot.

![much better](https://user-images.githubusercontent.com/10821510/33497348-ec1641ec-d6cd-11e7-9e60-e6922bad22cd.jpg)
