### ISSUE TITLE
Plugin update breaks Moodle 3.4 to blank screen

### ISSUE THREAD

**Issue by Paradiesgestalter** [thepurpleblob/moodle-block_course_overview#7]
I upgraded two Moodle instances from 3.3to 3.4, all seemed to work. but when I update block course_overview from 2017091100 to version 2017112800 or 2017120400 it gives me blank screen and I cannot access Moodle any more. Screws it completely. So I tried to delete the folder course_overview in folder blocks - now I can access the admin page again but it keeps me asking for update of the plugin and I cannot get out of that loop. can do nothing. Same if I upload the old version 2017091100: I can access the admin pages only to get asked for update, which leeds in blank page if I do so. How can I get rid of the plugin?

**Comment by thepurpleblob** [comment]
Is anything recorded in your web server error log? If there is something wrong in the block it would be nice to fix it. 

Simply deleting the block *should* work. Are you sure you haven't left an empty directory?

**Comment by thepurpleblob** [comment]
I just tried this myself and it worked fine. No blank page. The normal next step would be to enable debugging in your config.php (see config-dist.php section 7) and see what errors are logged when you recreate the problem.

**Comment by Paradiesgestalter** [comment]
Warning: require_once(/var/www/vhosts/example.com/httpdocs/akademie/blocks/course_overview/locallib.php): failed to open stream: No such file or directory in /var/www/vhosts/example.com/httpdocs/akademie/theme/flexibase/renderers/core_renderer.php on line 33

Fatal error: require_once(): Failed opening required '/var/www/vhosts/example.com/httpdocs/akademie/blocks/course_overview/locallib.php' (include_path='/var/www/vhosts/example.com/httpdocs/akademie/lib/pear:.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/example.com/httpdocs/akademie/theme/flexibase/renderers/core_renderer.php on line 33

**Comment by thepurpleblob** [comment]
That looks like a problem with the flexibase theme.

**Comment by thepurpleblob** [comment]
Bug submitted. Not an issue in course_overview block as far as I can see. 
https://github.com/roelmann/moodle-theme_flexibase/issues/101

**Comment by roelmann** [comment]
Just coming across this from the flexibase github - noting that flexibase is not supported on Moodle3.3+ (primarily due to this reason) What I have not tested is whether it will work if the version of the old course_overview block is installed from the plugins database.
Unfortunately this is due to the decision HQ made when the new dashboard was implemented and rather than deprecating the old block and leaving it in place for a few versions as is normal practice, they straight out removed it :(

**Comment by thepurpleblob** [comment]
It's available here as an optional plugin. I made some changes to get it to work at all and then I have enhanced it a bit so have probably completely broken it wrt the flexibase theme. Sorry - but I don't really have time to investigate this sort of issue.

**Comment by roelmann** [comment]
Yep - Sorry Howard, while I would love to get Flexibase upto scratch for 3.3+, I just dont have the time/capacity unless someone can fund it, so unfortunately I'm afraid the answer is a move to Boost as you said.
