### ISSUE TITLE
After installing the block on Moodle 3.3.3+, we get an "undefined" error when editing is turned on

### ISSUE THREAD

**Issue by chrismyers81** [thepurpleblob/moodle-block_course_overview#8]
After installing the latest version of the block on our Moodle 3.3.3+ instance, we get an "undefined" error popped up on the browser when editing is turned on:

https://www.screencast.com/t/WfA638BL34

It looks like this only happens if the Moodle "Debug Messages" option is set to something lower than "Normal".

I'm not really sure how to troubleshoot this beyond that?

**Comment by thepurpleblob** [comment]
Is that the 'clean' theme? Is there any chance that you could try with Javascript console enabled (View > Developer > Javascript Console) and see if any errors (red) are shown there.

**Comment by chrismyers81** [comment]
It is indeed. Here you go: http://susepaste.org/15610987

**Comment by chrismyers81** [comment]
(the server URL is https://moodletest.millikin.edu)

**Comment by thepurpleblob** [comment]
You've changed browsers. The first was Chrome I think :)
There seems to be an issue with the clean theme and font-awesome not related to the plugin. I'm not entirely sure what's going on here. I'll see if I can locate more info.

**Comment by chrismyers81** [comment]
OK cool, sounds good :) Please let me know if there's anything we can do to help troubleshoot it.

It looks like things look fine on the new boost theme.

And, sort of :P The first screenshot was from our Ed Tech folks, the second one was from me :)

**Comment by thepurpleblob** [comment]
I'm unable to reproduce this. I can't help thinking that it might be related to your other ticket.

**Comment by chrismyers81** [comment]
It's entirely possible?

**Comment by thepurpleblob** [comment]
I'm closing this as I cannot reproduce it.
