### ISSUE TITLE
CSS styling is cutting off the left-hand side of the course titles

### ISSUE THREAD

**Issue by chrismyers81** [thepurpleblob/moodle-block_course_overview#9]
When viewing our course list, the left-hand side of the course names are getting cut off. I fired up my developer tools, and it looks like the CSS is cutting it off: http://susepaste.org/91772632

I was able to fix it by using the developer tools to add a "padding-left" to the "tab-content" element: http://susepaste.org/82294466

**Comment by thepurpleblob** [comment]
What theme is this?

**Comment by gjb2048** [comment]
Hi Howard,

I can replicate this in Clean and Essential (3.4.0.1) in Moodle 3.4+ (Build: 20180104).  See: https://moodle.org/mod/forum/discuss.php?d=363681.  Its down to the use of BS3/4 grid classes and not BS2.3.2 grid classes - so need to 'react' to them.  This can be done in a plugin - see: https://github.com/gjb2048/moodle-format_topcoll/blob/master/renderer.php#L1118-L1138 and https://github.com/gjb2048/moodle-format_topcoll/blob/master/renderer.php#L81-L83 for detecting 'Boost'.  Third party themes can be instructed to override the get_row_class() and get_column_class() methods.

Gareth

**Comment by thepurpleblob** [comment]
I added some code to make it work better in clean et al. Well, I *thought* I did. Something strange going on...

**Comment by chrismyers81** [comment]
Awesome, thanks! Please let me know if there's any troubleshooting I can do to help out.

**Comment by lazydaisy** [comment]
What version of Moodle are you talking about here Gareth as my 3.4 version  of Clean theme looks ok...or am I missing something? Brain perhaps? Lol

**Comment by gjb2048** [comment]
2017120800 of the block and 20180104 of M3.4 as stated above Mary.

**Comment by thepurpleblob** [comment]
Sorry.... I'm not ignoring you. I've been crazy busy with some other work. I'll have a proper look at this in the next day or two. I'm pretty sure that I've done something stupid in committing changes.

**Comment by chrismyers81** [comment]
No worries at all; I haven't been very good at checking my GMail account as of late, so I totally missed your comment until just now :/
